### ISSUE TITLE
Implement CLI

### ISSUE THREAD

**Issue by moodysalem** [dlhdesign/node-aws-beanstalk#3]
Would like to use this plugin but I don't use gulp and would like to use npm scripts only for my builds and deploys

**Comment by dlhdesign** [comment]
The code package exports the `deploy` and `update` methods, so anything that can "require" the `index.js` file could make use of the library.
Gulp is used in the example mostly just to package up the repo code into a ZIP - which is required for application deployment (eg; copy ZIP to S3, deploy BeanStalk using S3 location). If you already have a ZIP from some other process, the key line, then, is just this:
`awsBeanstalk.deploy('./dist.zip', require("./beanstalk-config.js"), callback);`
