### ISSUE TITLE
 MissingSecurityHeader: Your request was missing a required header

### ISSUE THREAD

**Issue by eaidland** [dlhdesign/node-aws-beanstalk#4]
Hi!
I've updated my beanstalk-config.js file and the run the gulp deploy. 

Get this error message:
 MissingSecurityHeader: Your request was missing a required header

Where do I add the header?

Thanks

**Comment by seungjae87** [comment]
I meet same issue.

**Comment by compitDanielos** [comment]
+1

**Comment by gongmingqm10** [comment]
+1, hope it could be fixed.

**Comment by Code-Crash** [comment]
+1

**Comment by leighton-kuchel-smilemachine** [comment]
Try adding some additional information to bucketConfig. That seemed to fix the issue for me. You can view available options at:  [http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObjectAcl-property](url)

`bucketConfig: {
    Bucket: process.env.AWS_APP_BUCKET,
    ACL: "authenticated-read"
  }`

**Comment by dlhdesign** [comment]
As mentioned above; `bucketConfig` is used for accessing the S3 bucket, so anything added into that config is passed through into the S3 setup.
